### ISSUE TITLE
How is data availability proven?

### ISSUE THREAD

**Issue by TimTinkers** [succinctlabs/op-succinct#156]
Hello, I've read the [documentation](https://succinctlabs.github.io/op-succinct/architecture.html) and in this diagram I feel I understand everything except the data availability.

![image](https://github.com/user-attachments/assets/54633302-3cfb-414b-8022-6c9f169ac21b)

The OP Stack is running, presumably its `op-batcher` is still happily filling up blobs, and `op-succinct` is generating validity proofs for confirmation on L1. But how is the data from those blobs confirmed as part of the proof? I'm missing the link that takes this from validium to rollup.

Thank you!

**Comment by ratankaliani** [comment]
That's correct @Thegaram! In the future, when Optimism moves to using nonces for the `SystemConfig` and `DepositTransaction`'s, this derivation will become easier to prove.

**Comment by Thegaram** [comment]
Hi @ratankaliani, has this been added to the documentation? I haven't found the corresponding PR.

**Comment by ratankaliani** [comment]
Added it here @Thegaram: https://succinctlabs.github.io/op-succinct/faq.html
