### ISSUE TITLE
Improvement: Contract should not automatically finalize pre-upgrade pending roots

### ISSUE THREAD

**Issue by Thegaram** [succinctlabs/op-succinct#157]
The docs says

> ⚠️ Warning: All proposed, non-finalized output roots on the L2OutputOracleProxy will be automatically finalized after the upgrade to op-succinct, as the finalizationPeriod is set to 0 by default. For security, we recommend ensuring that all old proposer output roots are correct before upgrading.

Since these non-finalized output roots that were submitted right before the contract upgrade were not zk-verified, it is not safe for the bridge to consider them finalized.

I can think of two safer approaches:
1. Remove all unfinalized roots, and require `op-succinct-proposer` to re-submit them along with a proof.
2. Keep the original `finalizationPeriodSeconds` until all non-zk-finalized roots are finalized, then update it (to 0).

If this change is needed, I'm happy to submit a PR.

**Comment by ratankaliani** [comment]
2 is the right approach here - just requires a ramp-up period before the `finalizationPeriod` is set to 0. When upgrading an existing contract, we'll recommend that approach.
