### ISSUE TITLE
Upgrading OPSuccinctL2OutputOracle docs

### ISSUE THREAD

**Issue by jhkimqd** [succinctlabs/op-succinct#255]
When following the [Upgrading OPSuccinctL2OutputOracle](https://succinctlabs.github.io/op-succinct/advanced/l2-output-oracle.html#upgrading-opsuccinctl2outputoracle) docs, the upgrade transaction seems to get reverted.

![image](https://github.com/user-attachments/assets/038820f6-3957-40a9-8f80-6e21a628ceca)

**Comment by ratankaliani** [comment]
This is resolved by bumping the `reinitializer` on the contract. Will add this soon!

**Comment by ratankaliani** [comment]
Added to the docs here: https://succinctlabs.github.io/op-succinct/contracts/upgrade.html#manual-changes-to-opsuccinctl2outputoracle
