### ISSUE TITLE
Implement persistent SQLite DB across proposer runs

### ISSUE THREAD

**Issue by zobront** [succinctlabs/op-succinct#74]
If the proposer is reset, a new SQLite DB is created, which means that a number of proofs needs to be regenerated, despite being available on the prover network.

Allowing for a persistent SQLite DB link to be passed would allow the rebooted proposer to pick up where it left off.

Note that this would also require some logic to more gracefully handle REQs that are pending without a prover network ID upon reset. Even if the server is still working on these requests, they are being returned to the old proposer process, so we will never get the prover network id that's needed to manage the proof. Instead, these requests should be changed to UNREQ in order to repeat the request to the server.

**Comment by ratankaliani** [comment]
Resolved in https://github.com/succinctlabs/op-succinct/pull/115
